version: "3.5"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    links:
      - "php-82"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./trainings/:/var/www/html/

  php-82:
    build: ./docker-images/php-82
    container_name: php-82
    links:
      - "postgres:postgres"
      - "mailhog:mailhog"
    volumes:
      - ./trainings/:/var/www/html/

  postgres:
    image: postgres:13.12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'oro'
      POSTGRES_USER: 'orocommerce'
      POSTGRES_DB: 'oro'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
