services:
  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    decorates: oro_locale.entity_name_provider
    arguments:
      - '@.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -50}
