datagrids:
  contacts-grid:
    filters:
      columns:
        lastName:
          disabled: true
  user-naming-types-grid:
    acl_resource: training_user_naming_index
    extended_entity_name: Training\Bundle\UserNamingBundle\Entity\UserNamingType
    source:
      type: orm
      query:
        select:
          - type.id
          - type.title
          - type.format
        from:
          - { table: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType', alias: type }
    columns:
      title:
        label: 'training.usernaming.usernamingtype.title.label'
      format:
        label: 'training.usernaming.usernamingtype.format.label'
    filters:
      columns:
        title:
          type: string
          data_name: type.title
    sorters:
      columns:
        title:
          data_name: type.title
    properties:
      id: ~
      view_link:
        type: url
        route: training_user_naming_view
        params: [ id ]
      actions:
        view:
          type: navigate
          label: oro.grid.action.view
          icon: eye
          link: view_link
          rowAction: true



